dmadata_start: 0x1C050
variables:
  sMessageTableJPN: 0x801C1C48
  sMessageTableCredits: 0x801CA9D8
  gSoundFontTable: 0x801DFA80
  gSequenceFontTable: 0x801DFD10
  gSequenceTable:  0x801DFF20
  gSampleBankTable: 0x801E0730
archives:
  - map_i_static
  - map_grand_static
  - item_name_static
  - map_name_static
  - icon_item_static_yar
incbins:
  - name: ipl3
    segment: makerom
    vram: 0x8007F040
    size: 0xFC0
  - name: rspbootText
    segment: boot
    vram: 0x800978C0
    size: 0x160
  - name: cic6105Text
    segment: boot
    vram: 0x80097A20
    size: 0x20
  - name: aspMainText
    segment: code
    vram: 0x801A5BD0
    size: 0xFB0
  - name: gspS2DEX2_fifoText
    segment: code
    vram: 0x801A6B80
    size: 0x18C0
  - name: njpgdspMainText
    segment: code
    vram: 0x801A8440
    size: 0xAF0
  - name: aspMainData
    segment: code
    vram: 0x801E0770
    size: 0x2E0
  - name: gspF3DZEX2_NoN_PosLight_fifo_legacyText
    segment: code
    vram: 0x801E0A50
    size: 0x1390
  - name: gspF3DZEX2_NoN_PosLight_fifo_legacyData
    segment: code
    vram: 0x801E1DE0
    size: 0x420
  - name: gspF3DZEX2_NoN_PosLight_fifoText
    segment: code
    vram: 0x801E2200
    size: 0x1630
  - name: gspF3DZEX2_NoN_PosLight_fifoData
    segment: code
    vram: 0x801E3830
    size: 0x420
  - name: gspS2DEX2_fifoData
    segment: code
    vram: 0x801E3C50
    size: 0x390
  - name: njpgdspMainData
    segment: code
    vram: 0x801E3FE0
    size: 0x60
  - name: aspMainStack
    segment: code
    vram: 0x801D0BC0
    size: 0x400
assets:
