dmadata_start: 0x1A500
variables:
  sMessageTableNES: 0x801C6B98
  sMessageTableCredits: 0x801CFB08
  gSoundFontTable: 0x801E1180
  gSequenceFontTable: 0x801E1420
  gSequenceTable:  0x801E1630
  gSampleBankTable: 0x801E1E40
archives:
  - map_i_static
  - map_grand_static
  - item_name_static
  - map_name_static
  - icon_item_static_yar
  - icon_item_24_static_yar
  - schedule_dma_static_yar
incbins:
  - name: rspbootText
    segment: boot
    vram: 0x800969C0
    size: 0x160
  - name: aspMainText
    segment: code
    vram: 0x801AAAB0
    size: 0x1000
  - name: gspS2DEX2_fifoText
    segment: code
    vram: 0x801ABAB0
    size: 0x18C0
  - name: njpgdspMainText
    segment: code
    vram: 0x801AD370
    size: 0xAF0
  - name: aspMainData
    segment: code
    vram: 0x801E1E80
    size: 0x2E0
  - name: gspF3DZEX2_NoN_PosLight_fifoText
    segment: code
    vram: 0x801E2160
    size: 0x1630
  - name: gspF3DZEX2_NoN_PosLight_fifoData
    segment: code
    vram: 0x801E3790
    size: 0x420
  - name: gspS2DEX2_fifoData
    segment: code
    vram: 0x801E3BB0
    size: 0x390
  - name: njpgdspMainData
    segment: code
    vram: 0x801E3F40
    size: 0x60
assets:
